config/routes.rb
Rails.application.routes.draw do
  
  resources :products_substances
  resources :products_substances
  resources :products
  resources :presentations
  devise_for :users
  
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'newuser' => 'users#new'
  resources :clinics_people
  resources :clinics
  resources :specialties
  resources :people
  resources :cities
  resources :persontypes
  resources :person_types
  resources :products
  resources :medications
  resources :substances
  resources :categories
  resources :brands
  resources :presentations
  
  resources :users
  

  root 'static_pages#home'

  
  get 'products/:id/products_substances' => 'products_substances#index', as: :substances_index
  get 'products/:id/products_substances/new' => 'products_substances#new', as: :substances_new
  post 'products/:id/products_substances/new' => 'products_substances#create', as: :substances_create

end

app/models/brand.rb
class Brand < ActiveRecord::Base
	validates :brand, presence: true
	validates :person_id, presence: true
	belongs_to :medication
	belongs_to :person
	has_many :products
end

app/models/category.rb
class Category < ActiveRecord::Base
	validates :category, presence: true
	belongs_to :medication
	has_many :products
end

app/models/city.rb
class City < ActiveRecord::Base
	validates :city, presence: true
	has_many :people
	has_many :clinics
end

app/models/clinic.rb
class Clinic < ActiveRecord::Base
	has_and_belongs_to_many :people
	belongs_to :city
end

app/models/medication.rb
class Medication < ActiveRecord::Base
	validates :medication, presence: true
	validates :category_id, presence: true
	validates :brand_id, presence: true
	has_many :brands
	has_many :categories
	has_many :products, :dependent => :destroy
	has_many :substances, :through => :products
	accepts_nested_attributes_for :products
end

app/models/person.rb
class Person < ActiveRecord::Base
	validates :fullname, presence: true
	validates :address, presence: true
	validates :telephone, presence: true
	validates :birthday, presence: true
	validates :idperson, presence: true
	validates :city_id, presence: true
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }
	belongs_to :city
	belongs_to :specialty
	has_many :brands
	has_and_belongs_to_many :clinics
	has_and_belongs_to_many :persontypes
end

app/models/person_type.rb
class PersonType < ActiveRecord::Base
	has_many :persons
end

app/models/persontype.rb
class Persontype < ActiveRecord::Base
	validates :persontype, presence: true
	has_and_belongs_to_many :people
end

app/models/presentation.rb
class Presentation < ActiveRecord::Base
	validates :presentation, presence: true
	has_many :products
end

app/models/product.rb
class Product < ActiveRecord::Base
	validates :brand_id, presence: true
	validates :category_id, presence: true
	validates :presentation_id, presence: true
	belongs_to :brand
	belongs_to :category
	belongs_to :presentation
	has_many :substances, :through => :products_substance
end

app/models/products_substance.rb
class ProductsSubstance < ActiveRecord::Base
	validates :product_id, presence: true
	validates :substance_id, presence: true
	validates :concentration, presence: true
	validates :units, presence: true
	belongs_to :product
	belongs_to :substance
end

app/models/specialty.rb
class Specialty < ActiveRecord::Base
	validates :specialty, presence: true
	has_many :people
end

app/models/substance.rb
class Substance < ActiveRecord::Base
	validates :substance, presence: true
	has_many :substances, :through => :products_substance
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, #:registerable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/products_substances_controller.rb
class ProductsSubstancesController < ApplicationController
  before_action :set_products_substance, only: [:show, :edit, :update, :destroy]

  # GET /products_substances
  # GET /products_substances.json
  def index
    @products_substances = ProductsSubstance.where(product_id: params[:id])
  end

  # GET /products_substances/1
  # GET /products_substances/1.json
  def show
  end

  # GET /products_substances/new
  def new
    @products_substance = ProductsSubstance.new
  end

  # GET /products_substances/1/edit
  def edit
  end

  # POST /products_substances
  # POST /products_substances.json
  def create
    @products_substance = ProductsSubstance.new(products_substance_params)
    puts "hola"
    respond_to do |format|
      if @products_substance.save
        format.html { redirect_to @products_substance, notice: 'Products substance was successfully created.' }
        format.json { render :show, status: :created, location: @products_substance }
      else
        format.html { render :new }
        format.json { render json: @products_substance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products_substances/1
  # PATCH/PUT /products_substances/1.json
  def update
    respond_to do |format|
      if @products_substance.update(products_substance_params)
        format.html { redirect_to @products_substance, notice: 'Products substance was successfully updated.' }
        format.json { render :show, status: :ok, location: @products_substance }
      else
        format.html { render :edit }
        format.json { render json: @products_substance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products_substances/1
  # DELETE /products_substances/1.json
  def destroy
    @products_substance.destroy
    respond_to do |format|
      format.html { redirect_to products_substances_url, notice: 'Products substance was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_products_substance
      @products_substance = ProductsSubstance.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def products_substance_params
      params.require(:products_substance).permit(:product_id, :substance_id, :concentration, :units)
    end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/clinics_helper.rb
module ClinicsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/products_substances_helper.rb
module ProductsSubstancesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/products_substances/_form.html.erb
<%= form_for(@products_substance, url: substances_create_path(id: params[:id])) do |f| %>
  <% if @products_substance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@products_substance.errors.count, "error") %> prohibited this products_substance from being saved:</h2>

      <ul>
      <% @products_substance.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    
    <%= f.collection_select(:product_id, Product.all, :id, :product, {:selected => params[:id]}, {:hidden => "true" }) %>
  </div>
  <div class="field">
    <%= f.label :substance_id %><br>
    <%= f.collection_select(:substance_id, Substance.all, :id, :substance) %>
  </div>
  <div class="field">
    <%= f.label :concentration %><br>
    <%= f.text_field :concentration %>
  </div>
  <div class="field">
    <%= f.label :units %><br>
    <%= f.text_field :units %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products_substances/edit.html.erb
<h1>Editing Products Substance</h1>

<%= render 'form' %>

<%= link_to 'Show', @products_substance %> |
<%= link_to 'Back', products_substances_path %>

app/views/products_substances/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Products Substances</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Product</th>
      <th>Substance</th>
      <th>Concentration</th>
      <th>Units</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products_substances.each do |products_substance| %>
      <tr>
        <td><%= products_substance.product.product %></td>
        <td><%= products_substance.substance.substance %></td>
        <td><%= products_substance.concentration %></td>
        <td><%= products_substance.units %></td>
        <td><%= link_to 'Show', products_substance %></td>
        <td><%= link_to 'Edit', edit_products_substance_path(products_substance) %></td>
        <td><%= link_to 'Destroy', products_substance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Products substance', substances_new_path(params[:id]) %>

app/views/products_substances/new.html.erb
<h1>New Products Substance</h1>

<%= render 'form' %>

<%= link_to 'Back', products_substances_path %>

app/views/products_substances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @products_substance.product.product %>
</p>

<p>
  <strong>Substance:</strong>
  <%= @products_substance.substance.substance %>
</p>

<p>
  <strong>Concentration:</strong>
  <%= @products_substance.concentration %>
</p>

<p>
  <strong>Units:</strong>
  <%= @products_substance.units %>
</p>

<%= link_to 'Edit', edit_products_substance_path(@products_substance) %> |
<%= link_to 'Back', products_substances_path %>