config/routes.rb
Rails.application.routes.draw do
  
  resources :products_substances
  resources :products_substances
  resources :products
  resources :presentations
  devise_for :users
  
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'newuser' => 'users#new'
  resources :clinics_people
  resources :clinics
  resources :specialties
  resources :people
  resources :cities
  resources :persontypes
  resources :person_types
  resources :products
  resources :medications
  resources :substances
  resources :categories
  resources :brands
  resources :presentations
  
  resources :users
  

  root 'static_pages#home'

  
  get 'products/:id/products_substances' => 'products_substances#index', as: :substances_index
  get 'products/:id/products_substances/new' => 'products_substances#new', as: :substances_new
  post 'products/:id/products_substances/new' => 'products_substances#create', as: :substances_create

end

app/models/brand.rb
class Brand < ActiveRecord::Base
	validates :brand, presence: true
	validates :person_id, presence: true
	belongs_to :medication
	belongs_to :person
	has_many :products
end

app/models/category.rb
class Category < ActiveRecord::Base
	validates :category, presence: true
	belongs_to :medication
	has_many :products
end

app/models/city.rb
class City < ActiveRecord::Base
	validates :city, presence: true
	has_many :people
	has_many :clinics
end

app/models/clinic.rb
class Clinic < ActiveRecord::Base
	has_and_belongs_to_many :people
	belongs_to :city
end

app/models/medication.rb
class Medication < ActiveRecord::Base
	validates :medication, presence: true
	validates :category_id, presence: true
	validates :brand_id, presence: true
	has_many :brands
	has_many :categories
	has_many :products, :dependent => :destroy
	has_many :substances, :through => :products
	accepts_nested_attributes_for :products
end

app/models/person.rb
class Person < ActiveRecord::Base
	validates :fullname, presence: true
	validates :address, presence: true
	validates :telephone, presence: true
	validates :birthday, presence: true
	validates :idperson, presence: true
	validates :city_id, presence: true
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }
	belongs_to :city
	belongs_to :specialty
	has_many :brands
	has_and_belongs_to_many :clinics
	has_and_belongs_to_many :persontypes
end

app/models/person_type.rb
class PersonType < ActiveRecord::Base
	has_many :persons
end

app/models/persontype.rb
class Persontype < ActiveRecord::Base
	validates :persontype, presence: true
	has_and_belongs_to_many :people
end

app/models/presentation.rb
class Presentation < ActiveRecord::Base
	validates :presentation, presence: true
	has_many :products
end

app/models/product.rb
class Product < ActiveRecord::Base
	validates :brand_id, presence: true
	validates :category_id, presence: true
	validates :presentation_id, presence: true
	belongs_to :brand
	belongs_to :category
	belongs_to :presentation
	has_many :substances, :through => :products_substance
end

app/models/products_substance.rb
class ProductsSubstance < ActiveRecord::Base
	validates :product_id, presence: true
	validates :substance_id, presence: true
	validates :concentration, presence: true
	validates :units, presence: true
	belongs_to :product
	belongs_to :substance
end

app/models/specialty.rb
class Specialty < ActiveRecord::Base
	validates :specialty, presence: true
	has_many :people
end

app/models/substance.rb
class Substance < ActiveRecord::Base
	validates :substance, presence: true
	has_many :substances, :through => :products_substance
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, #:registerable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_action :set_brand, only: [:show, :edit, :update, :destroy]

  # GET /brands
  # GET /brands.json
  def index
    @brands = Brand.all
  end

  # GET /brands/1
  # GET /brands/1.json
  def show
  end

  # GET /brands/new
  def new
    @brand = Brand.new
  end

  # GET /brands/1/edit
  def edit
  end

  # POST /brands
  # POST /brands.json
  def create
    @brand = Brand.new(brand_params)

    respond_to do |format|
      if @brand.save
        format.html { redirect_to @brand, notice: 'Brand was successfully created.' }
        format.json { render :show, status: :created, location: @brand }
      else
        format.html { render :new }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /brands/1
  # PATCH/PUT /brands/1.json
  def update
    respond_to do |format|
      if @brand.update(brand_params)
        format.html { redirect_to @brand, notice: 'Brand was successfully updated.' }
        format.json { render :show, status: :ok, location: @brand }
      else
        format.html { render :edit }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brands/1
  # DELETE /brands/1.json
  def destroy
    @brand.destroy
    respond_to do |format|
      format.html { redirect_to brands_url, notice: 'Brand was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brand
      @brand = Brand.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brand_params
      params.require(:brand).permit(:brand, :person_id)
    end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/clinics_helper.rb
module ClinicsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/substances_helper.rb
module SubstancesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/brands/_form.html.erb
<%= form_for(@brand) do |f| %>
  <% if @brand.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@brand.errors.count, "error") %> prohibited this brand from being saved:</h2>

      <ul>
      <% @brand.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :brand %><br>
    <%= f.text_field :brand %>
  </div>
  <div class="field">
    <%= f.label :person_id %><br>
    <%= f.collection_select(:person_id, Person.all, :id, :fullname) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/brands/edit.html.erb
<h1>Editing Brand</h1>

<%= render 'form' %>

<%= link_to 'Show', @brand %> |
<%= link_to 'Back', brands_path %>

app/views/brands/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Brands</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Brand</th>
      <th>Person</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @brands.each do |brand| %>
      <tr>
        <td><%= brand.brand %></td>
        <td><%= brand.person.fullname %></td>
        <td><%= link_to 'Show', brand %></td>
        <td><%= link_to 'Edit', edit_brand_path(brand) %></td>
        <td><%= link_to 'Destroy', brand, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Brand', new_brand_path %>

app/views/brands/new.html.erb
<h1>New Brand</h1>

<%= render 'form' %>

<%= link_to 'Back', brands_path %>

app/views/brands/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Brand:</strong>
  <%= @brand.brand %>
</p>

<p>
  <strong>Person:</strong>
  <%= @brand.person.fullname %>
</p>

<%= link_to 'Edit', edit_brand_path(@brand) %> |
<%= link_to 'Back', brands_path %>