config/routes.rb
Rails.application.routes.draw do
  
  resources :products_substances
  resources :products_substances
  resources :products
  resources :presentations
  devise_for :users
  
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'newuser' => 'users#new'
  resources :clinics_people
  resources :clinics
  resources :specialties
  resources :people
  resources :cities
  resources :persontypes
  resources :person_types
  resources :products
  resources :medications
  resources :substances
  resources :categories
  resources :brands
  resources :presentations
  
  resources :users
  

  root 'static_pages#home'

  
  get 'products/:id/products_substances' => 'products_substances#index', as: :substances_index
  get 'products/:id/products_substances/new' => 'products_substances#new', as: :substances_new
  post 'products/:id/products_substances/new' => 'products_substances#create', as: :substances_create

end

app/models/brand.rb
class Brand < ActiveRecord::Base
	validates :brand, presence: true
	validates :person_id, presence: true
	belongs_to :medication
	belongs_to :person
	has_many :products
end

app/models/category.rb
class Category < ActiveRecord::Base
	validates :category, presence: true
	belongs_to :medication
	has_many :products
end

app/models/city.rb
class City < ActiveRecord::Base
	validates :city, presence: true
	has_many :people
	has_many :clinics
end

app/models/clinic.rb
class Clinic < ActiveRecord::Base
	has_and_belongs_to_many :people
	belongs_to :city
end

app/models/medication.rb
class Medication < ActiveRecord::Base
	validates :medication, presence: true
	validates :category_id, presence: true
	validates :brand_id, presence: true
	has_many :brands
	has_many :categories
	has_many :products, :dependent => :destroy
	has_many :substances, :through => :products
	accepts_nested_attributes_for :products
end

app/models/person.rb
class Person < ActiveRecord::Base
	validates :fullname, presence: true
	validates :address, presence: true
	validates :telephone, presence: true
	validates :birthday, presence: true
	validates :idperson, presence: true
	validates :city_id, presence: true
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }
	belongs_to :city
	belongs_to :specialty
	has_many :brands
	has_and_belongs_to_many :clinics
	has_and_belongs_to_many :persontypes
end

app/models/person_type.rb
class PersonType < ActiveRecord::Base
	has_many :persons
end

app/models/persontype.rb
class Persontype < ActiveRecord::Base
	validates :persontype, presence: true
	has_and_belongs_to_many :people
end

app/models/presentation.rb
class Presentation < ActiveRecord::Base
	validates :presentation, presence: true
	has_many :products
end

app/models/product.rb
class Product < ActiveRecord::Base
	validates :brand_id, presence: true
	validates :category_id, presence: true
	validates :presentation_id, presence: true
	belongs_to :brand
	belongs_to :category
	belongs_to :presentation
	has_many :substances, :through => :products_substance
end

app/models/products_substance.rb
class ProductsSubstance < ActiveRecord::Base
	validates :product_id, presence: true
	validates :substance_id, presence: true
	validates :concentration, presence: true
	validates :units, presence: true
	belongs_to :product
	belongs_to :substance
end

app/models/specialty.rb
class Specialty < ActiveRecord::Base
	validates :specialty, presence: true
	has_many :people
end

app/models/substance.rb
class Substance < ActiveRecord::Base
	validates :substance, presence: true
	has_many :substances, :through => :products_substance
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, #:registerable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:product, :category_id, :brand_id, :presentation_id)
    end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/clinics_helper.rb
module ClinicsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/substances_helper.rb
module SubstancesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product %><br>
    <%= f.text_field :product %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.collection_select(:category_id, Category.all, :id, :category) %>
  </div>
  <div class="field">
    <%= f.label :brand_id %><br>
    <%= f.collection_select(:brand_id, Brand.all, :id, :brand) %>
  </div>
  <div class="field">
    <%= f.label :presentation_id %><br>
    <%= f.collection_select(:presentation_id, Presentation.all, :id, :presentation) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Products</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Product</th>
      <th>Category</th>
      <th>Brand</th>
      <th>Presentation</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.product %></td>
        <td><%= product.category.category %></td>
        <td><%= product.brand.brand %></td>
        <td><%= product.presentation.presentation %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Set Substances', substances_index_path(product.id) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @product.product %>
</p>

<p>
  <strong>Category:</strong>
  <%= @product.category.category %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @product.brand.brand %>
</p>

<p>
  <strong>Presentation:</strong>
  <%= @product.presentation.presentation %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Set Substances', substances_new_path(params[:id]) %> |
<%= link_to 'Back', products_path %>